declare const styles: {
  chatbotContainer: string;
  floatingButton: string;
  magicalAppearance: string;
  floatingEffect: string;
  sparklesOverlay: string;
  sparkle: string;
  magicSmoke: string;
  smoke: string;
  lampRubAnimation: string;
  chatOpen: string;
  lampRubbed: string;
  rubbing: string;
  lampContainer: string;
  lampSvg: string;
  lampImageSmall: string;
  sparkleFloat: string;
  smokeRise: string;
  avatar: string;
  avatarSmall: string;
  chatWindow: string;
  genieEmergence: string;
  emerging: string;
  opening: string;
  closing: string;
  smoothGenieOpen: string;
  smoothGenieClose: string;
  genieEmergenceEnhanced: string;
  chatHeader: string;
  chatTitle: string;
  closeButton: string;
  chatBody: string;
  chatIframe: string;
  loadingOverlay: string;
  loadingSpinner: string;
  pulse: string;
  chatbotCopilotIframe: string;
  teams: string;
  welcome: string;
  welcomeImage: string;
  links: string;
};

export default styles;